# Index constants for accessing data in the Data Handler

from micropython import const


class EPS_CONST:
    MAINBOARD_VOLTAGE = const(0)
    MAINBOARD_CURRENT = const(1)
    BATTERY_PACK_SOC = const(2)
    BATTERY_PACK_REMAINING_CAPACITY_PERC = const(3)
    BATTERY_PACK_CURRENT = const(4)
    BATTERY_PACK_TEMPERATURE = const(5)
    BATTERY_PACK_VOLTAGE = const(6)
    BATTERY_PACK_MIDPOINT_VOLTAGE = const(7)
    BATTERY_CYCLES = const(8)
    BATTERY_PACK_TTE = const(9)
    BATTERY_PACK_TTF = const(10)
    BATTERY_TIME_SINCE_POWER_UP = const(11)
    XP_COIL_VOLTAGE = const(12)
    XP_COIL_CURRENT = const(13)
    XM_COIL_VOLTAGE = const(14)
    XM_COIL_CURRENT = const(15)
    YP_COIL_VOLTAGE = const(16)
    YP_COIL_CURRENT = const(17)
    YM_COIL_VOLTAGE = const(18)
    YM_COIL_CURRENT = const(19)
    ZP_COIL_VOLTAGE = const(20)
    ZP_COIL_CURRENT = const(21)
    ZM_COIL_VOLTAGE = const(22)
    ZM_COIL_CURRENT = const(23)
    JETSON_INPUT_VOLTAGE = const(24)
    JETSON_INPUT_CURRENT = const(25)
    RF_LDO_OUTPUT_VOLTAGE = const(26)
    RF_LDO_OUTPUT_CURRENT = const(27)
    GPS_VOLTAGE = const(28)
    GPS_CURRENT = const(29)
    XP_SOLAR_CHARGE_VOLTAGE = const(30)
    XP_SOLAR_CHARGE_CURRENT = const(31)
    XM_SOLAR_CHARGE_VOLTAGE = const(32)
    XM_SOLAR_CHARGE_CURRENT = const(33)
    YP_SOLAR_CHARGE_VOLTAGE = const(34)
    YP_SOLAR_CHARGE_CURRENT = const(35)
    YM_SOLAR_CHARGE_VOLTAGE = const(36)
    YM_SOLAR_CHARGE_CURRENT = const(37)
    ZP_SOLAR_CHARGE_VOLTAGE = const(38)
    ZP_SOLAR_CHARGE_CURRENT = const(39)
    ZM_SOLAR_CHARGE_VOLTAGE = const(40)
    ZM_SOLAR_CHARGE_CURRENT = const(41)


class SUN_IDX:
    TIME = const(0)
    STATUS = const(1)
    X = const(2)
    Y = const(3)
    Z = const(4)
    ECLIPSE = const(5)
