# Index constants for accessing data in the Data Handler

from micropython import const


class CDH_IDX:
    TIME = const(0)
    SC_STATE = const(1)
    SD_USAGE = const(2)
    CURRENT_RAM_USAGE = const(3)
    REBOOT_COUNT = const(4)
    WATCHDOG_TIMER = const(5)
    HAL_BITFLAGS = const(6)
    DETUMBLING_ERROR_FLAG = const(7)


class EPS_IDX:
    TIME_EPS = const(0)
    EPS_POWER_FLAG = const(1)
    MAINBOARD_TEMPERATURE = const(2)
    MAINBOARD_VOLTAGE = const(3)
    MAINBOARD_CURRENT = const(4)
    BATTERY_PACK_TEMPERATURE = const(5)
    BATTERY_PACK_REPORTED_SOC = const(6)
    BATTERY_PACK_REPORTED_CAPACITY = const(7)
    BATTERY_PACK_CURRENT = const(8)
    BATTERY_PACK_VOLTAGE = const(9)
    BATTERY_PACK_MIDPOINT_VOLTAGE = const(10)
    BATTERY_PACK_TTE = const(11)
    BATTERY_PACK_TTF = const(12)
    XP_COIL_VOLTAGE = const(13)
    XP_COIL_CURRENT = const(14)
    XM_COIL_VOLTAGE = const(15)
    XM_COIL_CURRENT = const(16)
    YP_COIL_VOLTAGE = const(17)
    YP_COIL_CURRENT = const(18)
    YM_COIL_VOLTAGE = const(19)
    YM_COIL_CURRENT = const(20)
    ZP_COIL_VOLTAGE = const(21)
    ZP_COIL_CURRENT = const(22)
    ZM_COIL_VOLTAGE = const(23)
    ZM_COIL_CURRENT = const(24)
    JETSON_INPUT_VOLTAGE = const(25)
    JETSON_INPUT_CURRENT = const(26)
    RF_LDO_OUTPUT_VOLTAGE = const(27)
    RF_LDO_OUTPUT_CURRENT = const(28)
    GPS_VOLTAGE = const(29)
    GPS_CURRENT = const(30)
    XP_SOLAR_CHARGE_VOLTAGE = const(31)
    XP_SOLAR_CHARGE_CURRENT = const(32)
    XM_SOLAR_CHARGE_VOLTAGE = const(33)
    XM_SOLAR_CHARGE_CURRENT = const(34)
    YP_SOLAR_CHARGE_VOLTAGE = const(35)
    YP_SOLAR_CHARGE_CURRENT = const(36)
    YM_SOLAR_CHARGE_VOLTAGE = const(37)
    YM_SOLAR_CHARGE_CURRENT = const(38)
    ZP_SOLAR_CHARGE_VOLTAGE = const(39)
    ZP_SOLAR_CHARGE_CURRENT = const(40)
    ZM_SOLAR_CHARGE_VOLTAGE = const(41)
    ZM_SOLAR_CHARGE_CURRENT = const(42)


class EPS_WARNING_IDX:
    TIME_EPS_WARNING = const(0)
    MAINBOARD_POWER_ALERT = const(1)
    RADIO_POWER_ALERT = const(2)
    JETSON_POWER_ALERT = const(3)
    XP_COIL_POWER_ALERT = const(4)
    XM_COIL_POWER_ALERT = const(5)
    YP_COIL_POWER_ALERT = const(6)
    YM_COIL_POWER_ALERT = const(7)
    ZP_COIL_POWER_ALERT = const(8)
    ZM_COIL_POWER_ALERT = const(9)


class ADCS_IDX:
    TIME_ADCS = const(0)
    MODE = const(1)
    GYRO_X = const(2)
    GYRO_Y = const(3)
    GYRO_Z = const(4)
    MAG_X = const(5)
    MAG_Y = const(6)
    MAG_Z = const(7)
    SUN_STATUS = const(8)
    SUN_VEC_X = const(9)
    SUN_VEC_Y = const(10)
    SUN_VEC_Z = const(11)
    LIGHT_SENSOR_XP = const(12)
    LIGHT_SENSOR_XM = const(13)
    LIGHT_SENSOR_YP = const(14)
    LIGHT_SENSOR_YM = const(15)
    LIGHT_SENSOR_ZP1 = const(16)
    LIGHT_SENSOR_ZP2 = const(17)
    LIGHT_SENSOR_ZP3 = const(18)
    LIGHT_SENSOR_ZP4 = const(19)
    LIGHT_SENSOR_ZM = const(20)
    XP_COIL_STATUS = const(21)
    XM_COIL_STATUS = const(22)
    YP_COIL_STATUS = const(23)
    YM_COIL_STATUS = const(24)
    ZP_COIL_STATUS = const(25)
    ZM_COIL_STATUS = const(26)
    ATTITUDE_QW = const(27)
    ATTITUDE_QX = const(28)
    ATTITUDE_QY = const(29)
    ATTITUDE_QZ = const(30)


class GPS_IDX:
    TIME_GPS = const(0)
    GPS_MESSAGE_ID = const(1)
    GPS_FIX_MODE = const(2)
    GPS_NUMBER_OF_SV = const(3)
    GPS_GNSS_WEEK = const(4)
    GPS_GNSS_TOW = const(5)
    GPS_LATITUDE = const(6)
    GPS_LONGITUDE = const(7)
    GPS_ELLIPSOID_ALT = const(8)
    GPS_MEAN_SEA_LVL_ALT = const(9)
    GPS_GDOP = const(10)
    GPS_PDOP = const(11)
    GPS_HDOP = const(12)
    GPS_VDOP = const(13)
    GPS_TDOP = const(14)
    GPS_ECEF_X = const(15)
    GPS_ECEF_Y = const(16)
    GPS_ECEF_Z = const(17)
    GPS_ECEF_VX = const(18)
    GPS_ECEF_VY = const(19)
    GPS_ECEF_VZ = const(20)


class PAYLOAD_IDX:
    pass


class STORAGE_IDX:
    NUM_FILES = const(0)
    DIR_SIZE = const(1)


class HAL_IDX:
    TIME_HAL = const(0)
    SDCARD_ERROR = const(1)
    SDCARD_ERROR_COUNT = const(2)
    RTC_ERROR = const(3)
    RTC_ERROR_COUNT = const(4)
    GPS_ERROR = const(5)
    GPS_ERROR_COUNT = const(6)
    RADIO_ERROR = const(7)
    RADIO_ERROR_COUNT = const(8)
    IMU_ERROR = const(9)
    IMU_ERROR_COUNT = const(10)
    FUEL_GAUGE_ERROR = const(11)
    FUEL_GAUGE_ERROR_COUNT = const(12)
    BATT_HEATERS_ERROR = const(13)
    BATT_HEATERS_ERROR_COUNT = const(14)
    WATCHDOG_ERROR = const(15)
    WATCHDOG_ERROR_COUNT = const(16)
    BURN_WIRES_ERROR = const(17)
    BURN_WIRES_ERROR_COUNT = const(18)
    BOARD_PWR_ERROR = const(19)
    BOARD_PWR_ERROR_COUNT = const(20)
    RADIO_PWR_ERROR = const(21)
    RADIO_PWR_ERROR_COUNT = const(22)
    GPS_PWR_ERROR = const(23)
    GPS_PWR_ERROR_COUNT = const(24)
    JETSON_PWR_ERROR = const(25)
    JETSON_PWR_ERROR_COUNT = const(26)
    XP_PWR_ERROR = const(27)
    XP_PWR_ERROR_COUNT = const(28)
    XM_PWR_ERROR = const(29)
    XM_PWR_ERROR_COUNT = const(30)
    YP_PWR_ERROR = const(31)
    YP_PWR_ERROR_COUNT = const(32)
    YM_PWR_ERROR = const(33)
    YM_PWR_ERROR_COUNT = const(34)
    ZP_PWR_ERROR = const(35)
    ZP_PWR_ERROR_COUNT = const(36)
    TORQUE_XP_ERROR = const(37)
    TORQUE_XP_ERROR_COUNT = const(38)
    TORQUE_XM_ERROR = const(39)
    TORQUE_XM_ERROR_COUNT = const(40)
    TORQUE_YP_ERROR = const(41)
    TORQUE_YP_ERROR_COUNT = const(42)
    TORQUE_YM_ERROR = const(43)
    TORQUE_YM_ERROR_COUNT = const(44)
    TORQUE_ZP_ERROR = const(45)
    TORQUE_ZP_ERROR_COUNT = const(46)
    TORQUE_ZM_ERROR = const(47)
    TORQUE_ZM_ERROR_COUNT = const(48)
    LIGHT_XP_ERROR = const(49)
    LIGHT_XP_ERROR_COUNT = const(50)
    LIGHT_XM_ERROR = const(51)
    LIGHT_XM_ERROR_COUNT = const(52)
    LIGHT_YP_ERROR = const(53)
    LIGHT_YP_ERROR_COUNT = const(54)
    LIGHT_YM_ERROR = const(55)
    LIGHT_YM_ERROR_COUNT = const(56)
    LIGHT_ZM_ERROR = const(57)
    LIGHT_ZM_ERROR_COUNT = const(58)
    LIGHT_ZP_1_ERROR = const(59)
    LIGHT_ZP_1_ERROR_COUNT = const(60)
    LIGHT_ZP_2_ERROR = const(61)
    LIGHT_ZP_2_ERROR_COUNT = const(62)
    LIGHT_ZP_3_ERROR = const(63)
    LIGHT_ZP_3_ERROR_COUNT = const(64)
    LIGHT_ZP_4_ERROR = const(65)
    LIGHT_ZP_4_ERROR_COUNT = const(66)
    PERIPH_REBOOT_COUNT = const(67)


"""
Helper function to get the number of attributes in a class
This result should be static
"""


def class_length(cls):
    return len([attr for attr in dir(cls) if not callable(getattr(cls, attr)) and not attr.startswith("__")])
