name: HIL CI

on:
  push: 

jobs:
  hil-test:
    runs-on: [self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Flash Mainboard
        run: |
          cd ~/FSW-mainboard
          sudo minicom -D /dev/ttyACM0 -b 115200 -S build_tools/exit_to_repl.minicom
          sudo ./run.sh /media/argus/ARGUS/

      - name: Run smoke test (5 min)
        run: |
          cd ~/FSW-mainboard
          timeout 300s sudo minicom -D /dev/ttyACM0 -b 115200 -C smoke_output.log -S build_tools/reset_board.minicom
          sudo minicom -D /dev/ttyACM0 -b 115200 -S build_tools/exit_to_repl.minicom

      - name: View serial output (tail)
        run: |
          cd ~/FSW-mainboard
          tail -n 50 smoke_output.log

      - name: Upload serial log as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hil-smoke-log
          path: ~/FSW-mainboard/smoke_output.log
